import { Global, Module } from '@nestjs/common';
import { CqrsModule } from '@nestjs/cqrs';

import {
  AuthenticateUserHandler,
  RequestPasswordResetHandler,
  ResetUserPasswordHandler,
  CompleteNewUserRegistrationInvitationHandler,
  CreateMasterUserHandler,
  CreateMasterUserRegistrationInvitationHandler,
  CreateUserRegistrationInvitationHandler,
  CreateUserAndNotifyHandler,
  UpdateUserHandler,
  UpdateMyProfileHandler,
  DeleteUserHandler,
  UploadFilesHandler,
  CreateServiceEntryHandler,
  IngestServicePackageHandler,
  DeleteServicePackageRecordHandler,
  UpdateServiceEntryHandler,
  DeleteServiceEntryHandler,
  SubmitServiceEntrySurveyHandler,
  CreateCustomerFiscalProfileHandler,
  SubmitCustomerFiscalProfileHandler,
  UpdateCustomerHandler,
  DeleteCustomerHandler,
  CreateProviderHandler,
  UpdateProviderHandler,
  DeleteProviderHandler,
} from '@infra/cqrs/commands';
import {
  GetUserByIdHandler,
  GetUserRegistrationInvitationHandler,
  GetUsersHandler,
  GetFileByIdHandler,
  DownloadFileHandler,
  GetUserRolesHandler,
  GetServiceEntriesHandler,
  GetServiceEntryByIdHandler,
  GetServiceEntryByTokenHandler,
  GetServiceEntrySurveyStatsHandler,
  GetServiceEntrySurveyResponsesHandler,
  GetServiceCategoriesHandler,
  GetCustomerFiscalProfilesHandler,
  GetCustomerFiscalProfileByIdHandler,
  GetCustomerFiscalProfileByTokenHandler,
  GetServicePackageRecordsHandler,
  GetServicePackageRecordByIdHandler,
  GetProvidersHandler,
  GetProviderByIdHandler,
} from '@infra/cqrs/queries';

const providers = [
  AuthenticateUserHandler,
  RequestPasswordResetHandler,
  ResetUserPasswordHandler,
  CreateUserAndNotifyHandler,
  CreateMasterUserHandler,
  CreateUserRegistrationInvitationHandler,
  CreateMasterUserRegistrationInvitationHandler,
  CompleteNewUserRegistrationInvitationHandler,
  GetUserRegistrationInvitationHandler,
  GetUsersHandler,
  GetUserByIdHandler,
  UpdateUserHandler,
  UpdateMyProfileHandler,
  DeleteUserHandler,
  UploadFilesHandler,
  CreateServiceEntryHandler,
  IngestServicePackageHandler,
  DeleteServicePackageRecordHandler,
  UpdateServiceEntryHandler,
  DeleteServiceEntryHandler,
  SubmitServiceEntrySurveyHandler,
  CreateCustomerFiscalProfileHandler,
  SubmitCustomerFiscalProfileHandler,
  UpdateCustomerHandler,
  DeleteCustomerHandler,
  CreateProviderHandler,
  UpdateProviderHandler,
  DeleteProviderHandler,
  GetFileByIdHandler,
  DownloadFileHandler,
  GetUserRolesHandler,
  GetServiceEntriesHandler,
  GetServiceEntryByIdHandler,
  GetServiceEntryByTokenHandler,
  GetServiceEntrySurveyStatsHandler,
  GetServiceEntrySurveyResponsesHandler,
  GetServiceCategoriesHandler,
  GetCustomerFiscalProfilesHandler,
  GetCustomerFiscalProfileByIdHandler,
  GetCustomerFiscalProfileByTokenHandler,
  GetServicePackageRecordsHandler,
  GetServicePackageRecordByIdHandler,
  GetProvidersHandler,
  GetProviderByIdHandler,
];

@Global()
@Module({
  imports: [CqrsModule],
  providers,
})
export class GlobalCqrsModule {}
