import { DomainException } from './domain.exception';

export enum EntityNotFoundExceptionCode {
  USER = 'ENTITY_NOT_FOUND.USER',
  USER_REGISTRATION_INVITATION = 'ENTITY_NOT_FOUND.USER_REGISTRATION_INVITATION',
  FILE = 'ENTITY_NOT_FOUND.FILE',
  SERVICE_ENTRY = 'ENTITY_NOT_FOUND.SERVICE_ENTRY',
  USER_PASSWORD_RESET_TOKEN = 'ENTITY_NOT_FOUND.USER_PASSWORD_RESET_TOKEN',
  CUSTOMER = 'ENTITY_NOT_FOUND.CUSTOMER',
  CUSTOMER_FISCAL_PROFILE = 'ENTITY_NOT_FOUND.CUSTOMER_FISCAL_PROFILE',
  SERVICE_PACKAGE_RECORD = 'ENTITY_NOT_FOUND.SERVICE_PACKAGE_RECORD',
  PROVIDER = 'ENTITY_NOT_FOUND.PROVIDER',
  PROVIDER_FISCAL_PROFILE = 'ENTITY_NOT_FOUND.PROVIDER_FISCAL_PROFILE',
  PROVIDER_BANKING_INFO = 'ENTITY_NOT_FOUND.PROVIDER_BANKING_INFO',
  ROLE = 'ENTITY_NOT_FOUND.ROLE',
  CONTACT = 'ENTITY_NOT_FOUND.CONTACT',
  RECIPIENT_GROUP = 'ENTITY_NOT_FOUND.RECIPIENT_GROUP',
  EXPIRATION_STATUS_POLICY = 'ENTITY_NOT_FOUND.EXPIRATION_STATUS_POLICY',
  EXPIRATION_NOTIFICATION_POLICY = 'ENTITY_NOT_FOUND.EXPIRATION_NOTIFICATION_POLICY',
}

export class EntityNotFoundException extends DomainException {
  constructor(
    code: EntityNotFoundExceptionCode,
    details: Record<string, any> = {} as Record<string, any>,
  ) {
    super(code, details);
  }

  static create(
    code: EntityNotFoundExceptionCode,
    details: Record<string, any> = {},
  ) {
    return new EntityNotFoundException(code, details);
  }
}
