import { DomainException } from './domain.exception';

export class EntityAlreadyExistsException extends DomainException {
  constructor(
    code: EntityAlreadyExistsExceptionCode,
    details: Record<string, any> = {},
  ) {
    super(code, details);
  }

  static create(
    code: EntityAlreadyExistsExceptionCode,
    details: Record<string, any> = {},
  ): EntityAlreadyExistsException {
    return new EntityAlreadyExistsException(code, details);
  }
}

export enum EntityAlreadyExistsExceptionCode {
  USER_EMAIL = 'ENTITY_ALREADY_EXISTS.USER.EMAIL',
  USER_REGISTRATION_INVITATION_EMAIL = 'ENTITY_ALREADY_EXISTS.USER_REGISTRATION_INVITATION.EMAIL',
  SERVICE_ENTRY_ORDER = 'ENTITY_ALREADY_EXISTS.SERVICE_ENTRY.ORDER',
  SERVICE_ENTRY_SURVEY = 'ENTITY_ALREADY_EXISTS.SERVICE_ENTRY.SURVEY',
  CUSTOMER_FISCAL_PROFILE_CODE = 'ENTITY_ALREADY_EXISTS.CUSTOMER_FISCAL_PROFILE.CLIENT_CODE',
  CUSTOMER_FISCAL_PROFILE_FORM = 'ENTITY_ALREADY_EXISTS.CUSTOMER_FISCAL_PROFILE.FORM',
  PROVIDER_CODE = 'ENTITY_ALREADY_EXISTS.PROVIDER.PROVIDER_CODE',
  PROVIDER_FISCAL_PROFILE_FORM = 'ENTITY_ALREADY_EXISTS.PROVIDER_FISCAL_PROFILE.FORM',
  PROVIDER_BANKING_INFO_FORM = 'ENTITY_ALREADY_EXISTS.PROVIDER_BANKING_INFO.FORM',
  ROLE_NAME = 'ENTITY_ALREADY_EXISTS.ROLE.NAME',
  ROLE_CODE = 'ENTITY_ALREADY_EXISTS.ROLE.CODE',
  CONTACT_USER = 'ENTITY_ALREADY_EXISTS.CONTACT.USER',
  RECIPIENT_GROUP_NAME = 'ENTITY_ALREADY_EXISTS.RECIPIENT_GROUP.NAME',
  RECIPIENT_GROUP_CODE = 'ENTITY_ALREADY_EXISTS.RECIPIENT_GROUP.CODE',
}
