export const INTERNAL_ASSET_MAINTENANCE_TYPES = {
  CALIBRATION: {
    code: 'CALIBRATION',
    nameKey: 'INTERNAL_ASSET_MAINTENANCE_RECORD.TYPE.CALIBRATION',
  },
  VERIFICATION: {
    code: 'VERIFICATION',
    nameKey: 'INTERNAL_ASSET_MAINTENANCE_RECORD.TYPE.VERIFICATION',
  },
  PREVENTIVE_MAINTENANCE: {
    code: 'PREVENTIVE_MAINTENANCE',
    nameKey: 'INTERNAL_ASSET_MAINTENANCE_RECORD.TYPE.PREVENTIVE_MAINTENANCE',
  },
  PROVIDER_PAYMENT: {
    code: 'PROVIDER_PAYMENT',
    nameKey: 'INTERNAL_ASSET_MAINTENANCE_RECORD.TYPE.PROVIDER_PAYMENT',
  },
  QUOTATION_DELIVERY: {
    code: 'QUOTATION_DELIVERY',
    nameKey: 'INTERNAL_ASSET_MAINTENANCE_RECORD.TYPE.QUOTATION_DELIVERY',
  },
} as const;

export type InternalAssetMaintenanceTypeCode =
  keyof typeof INTERNAL_ASSET_MAINTENANCE_TYPES;
