import { AuthorizationOperationCode } from './authorization-operations.catalog';

export const AUTHORIZATION_CATALOG = {
  USERS: {
    code: 'USERS',
    nameKey: 'AUTHORIZATION.MODULE.USERS',
    operations: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  },
  ROLES: {
    code: 'ROLES',
    nameKey: 'AUTHORIZATION.MODULE.ROLES',
    operations: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  },
  CUSTOMERS: {
    code: 'CUSTOMERS',
    nameKey: 'AUTHORIZATION.MODULE.CUSTOMERS',
    operations: ['CREATE', 'READ', 'READ_PUBLIC_ACCESS', 'UPDATE', 'DELETE'],
  },
  PROVIDERS: {
    code: 'PROVIDERS',
    nameKey: 'AUTHORIZATION.MODULE.PROVIDERS',
    operations: ['CREATE', 'READ', 'READ_PUBLIC_ACCESS', 'UPDATE', 'DELETE'],
  },
  SERVICE_ENTRIES: {
    code: 'SERVICE_ENTRIES',
    nameKey: 'AUTHORIZATION.MODULE.SERVICE_ENTRIES',
    operations: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  },
  SERVICE_ENTRY_SURVEYS: {
    code: 'SERVICE_ENTRY_SURVEYS',
    nameKey: 'AUTHORIZATION.MODULE.SERVICE_ENTRY_SURVEYS',
    operations: ['READ'],
  },
  SERVICE_PACKAGES: {
    code: 'SERVICE_PACKAGES',
    nameKey: 'AUTHORIZATION.MODULE.SERVICE_PACKAGES',
    operations: ['READ', 'DELETE'],
  },
  USER_REGISTRATION_INVITATIONS: {
    code: 'USER_REGISTRATION_INVITATIONS',
    nameKey: 'AUTHORIZATION.MODULE.USER_REGISTRATION_INVITATIONS',
    operations: ['CREATE', 'READ', 'RESEND', 'REVOKE'],
  },
  CONTACTS: {
    code: 'CONTACTS',
    nameKey: 'AUTHORIZATION.MODULE.CONTACTS',
    operations: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  },
  RECIPIENT_GROUPS: {
    code: 'RECIPIENT_GROUPS',
    nameKey: 'AUTHORIZATION.MODULE.RECIPIENT_GROUPS',
    operations: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  },
  EXPIRATION_STATUS_POLICIES: {
    code: 'EXPIRATION_STATUS_POLICIES',
    nameKey: 'AUTHORIZATION.MODULE.EXPIRATION_STATUS_POLICIES',
    operations: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  },
  EXPIRATION_NOTIFICATION_POLICIES: {
    code: 'EXPIRATION_NOTIFICATION_POLICIES',
    nameKey: 'AUTHORIZATION.MODULE.EXPIRATION_NOTIFICATION_POLICIES',
    operations: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  },
  INTERNAL_ASSET_MAINTENANCE_RECORDS: {
    code: 'INTERNAL_ASSET_MAINTENANCE_RECORDS',
    nameKey: 'AUTHORIZATION.MODULE.INTERNAL_ASSET_MAINTENANCE_RECORDS',
    operations: ['CREATE', 'READ', 'UPDATE', 'DELETE'],
  },
  CUSTOMER_SERVICE_RECORDS: {
    code: 'CUSTOMER_SERVICE_RECORDS',
    nameKey: 'AUTHORIZATION.MODULE.CUSTOMER_SERVICE_RECORDS',
    operations: ['CREATE', 'READ', 'UPDATE', 'DELETE', 'MANAGE_SERVICE_TYPES'],
  },
  CUSTOMER_SERVICE_RECORDS_CLIENT_ACCESS: {
    code: 'CUSTOMER_SERVICE_RECORDS_CLIENT_ACCESS',
    nameKey: 'AUTHORIZATION.MODULE.CUSTOMER_SERVICE_RECORDS_CLIENT_ACCESS',
    operations: ['READ'],
  },
} as const satisfies Record<
  string,
  {
    code: string;
    nameKey: string;
    operations: AuthorizationOperationCode[];
  }
>;

export type AuthorizationModuleCode = keyof typeof AUTHORIZATION_CATALOG;
