import {
  MongooseUserRegistrationInvitationReadRepositoryImpl,
  MongooseUserRegistrationInvitationWriteRepositoryImpl,
  MongooseUserReadRepositoryImpl,
  MongooseUserWriteRepositoryImpl,
  MongooseRoleReadRepositoryImpl,
  MongooseRoleWriteRepositoryImpl,
  MongooseUserPasswordResetTokenReadRepositoryImpl,
  MongooseUserPasswordResetTokenWriteRepositoryImpl,
  MongooseFileReadRepositoryImpl,
  MongooseFileWriteRepositoryImpl,
  MongooseServiceEntryReadRepositoryImpl,
  MongooseServiceEntryWriteRepositoryImpl,
  MongooseServiceEntryAccessReadRepositoryImpl,
  MongooseServiceEntryAccessWriteRepositoryImpl,
  MongooseServiceEntrySurveyReadRepositoryImpl,
  MongooseServiceEntrySurveyWriteRepositoryImpl,
  MongooseServiceEntrySurveyTemplateReadRepositoryImpl,
  MongooseCustomerFiscalProfileReadRepositoryImpl,
  MongooseCustomerFiscalProfileWriteRepositoryImpl,
  MongooseCustomerReadRepositoryImpl,
  MongooseCustomerWriteRepositoryImpl,
  MongooseServicePackageRecordWriteRepositoryImpl,
  MongooseServicePackageRecordReadRepositoryImpl,
  MongooseProviderReadRepositoryImpl,
  MongooseProviderWriteRepositoryImpl,
  MongooseProviderFiscalProfileReadRepositoryImpl,
  MongooseProviderFiscalProfileWriteRepositoryImpl,
  MongooseProviderBankingInfoReadRepositoryImpl,
  MongooseProviderBankingInfoWriteRepositoryImpl,
  MongooseContactReadRepositoryImpl,
  MongooseContactWriteRepositoryImpl,
  MongooseRecipientGroupReadRepositoryImpl,
  MongooseRecipientGroupWriteRepositoryImpl,
  MongooseExpirationStatusPolicyReadRepositoryImpl,
  MongooseExpirationStatusPolicyWriteRepositoryImpl,
  MongooseExpirationNotificationPolicyReadRepositoryImpl,
  MongooseExpirationNotificationPolicyWriteRepositoryImpl,
  MongooseInternalAssetMaintenanceRecordReadRepositoryImpl,
  MongooseInternalAssetMaintenanceRecordWriteRepositoryImpl,
  MongooseInternalJobLockRepositoryImpl,
  MongooseUserCustomerRelationshipReadRepositoryImpl,
  MongooseUserCustomerRelationshipWriteRepositoryImpl,
} from '.';

import {
  IUserRegistrationInvitationReadRepositoryToken,
  IUserRegistrationInvitationWriteRepositoryToken,
  IUserReadRepositoryToken,
  IUserWriteRepositoryToken,
  IRoleReadRepositoryToken,
  IRoleWriteRepositoryToken,
  IUserPasswordResetTokenReadRepositoryToken,
  IUserPasswordResetTokenWriteRepositoryToken,
  IFileReadRepositoryToken,
  IFileWriteRepositoryToken,
  IServiceEntryReadRepositoryToken,
  IServiceEntryWriteRepositoryToken,
  IServiceEntryAccessReadRepositoryToken,
  IServiceEntryAccessWriteRepositoryToken,
  IServiceEntrySurveyReadRepositoryToken,
  IServiceEntrySurveyWriteRepositoryToken,
  IServiceEntrySurveyTemplateReadRepositoryToken,
  ICustomerFiscalProfileReadRepositoryToken,
  ICustomerFiscalProfileWriteRepositoryToken,
  ICustomerReadRepositoryToken,
  ICustomerWriteRepositoryToken,
  IServicePackageRecordWriteRepositoryToken,
  IServicePackageRecordReadRepositoryToken,
  IProviderReadRepositoryToken,
  IProviderWriteRepositoryToken,
  IProviderFiscalProfileReadRepositoryToken,
  IProviderFiscalProfileWriteRepositoryToken,
  IProviderBankingInfoReadRepositoryToken,
  IProviderBankingInfoWriteRepositoryToken,
  IContactReadRepositoryToken,
  IContactWriteRepositoryToken,
  IRecipientGroupReadRepositoryToken,
  IRecipientGroupWriteRepositoryToken,
  IExpirationStatusPolicyReadRepositoryToken,
  IExpirationStatusPolicyWriteRepositoryToken,
  IExpirationNotificationPolicyReadRepositoryToken,
  IExpirationNotificationPolicyWriteRepositoryToken,
  IInternalAssetMaintenanceRecordReadRepositoryToken,
  IInternalAssetMaintenanceRecordWriteRepositoryToken,
  IInternalJobLockRepositoryToken,
  IUserCustomerRelationshipReadRepositoryToken,
  IUserCustomerRelationshipWriteRepositoryToken,
} from '@domain/ports/repositories';
import { ITransactionalExecutorToken } from '@domain/ports/services';
import {
  MongooseTransactionContext,
  MongooseTransactionalExecutor,
} from '@infra/persistence/mongoose/transactions';

export const MongooseRepositoriesConfig = [
  {
    provide: IUserReadRepositoryToken,
    useClass: MongooseUserReadRepositoryImpl,
  },
  {
    provide: IUserWriteRepositoryToken,
    useClass: MongooseUserWriteRepositoryImpl,
  },
  {
    provide: IRoleReadRepositoryToken,
    useClass: MongooseRoleReadRepositoryImpl,
  },
  {
    provide: IRoleWriteRepositoryToken,
    useClass: MongooseRoleWriteRepositoryImpl,
  },
  {
    provide: IUserRegistrationInvitationReadRepositoryToken,
    useClass: MongooseUserRegistrationInvitationReadRepositoryImpl,
  },
  {
    provide: IUserRegistrationInvitationWriteRepositoryToken,
    useClass: MongooseUserRegistrationInvitationWriteRepositoryImpl,
  },
  {
    provide: IUserPasswordResetTokenReadRepositoryToken,
    useClass: MongooseUserPasswordResetTokenReadRepositoryImpl,
  },
  {
    provide: IUserPasswordResetTokenWriteRepositoryToken,
    useClass: MongooseUserPasswordResetTokenWriteRepositoryImpl,
  },
  {
    provide: IFileReadRepositoryToken,
    useClass: MongooseFileReadRepositoryImpl,
  },
  {
    provide: IFileWriteRepositoryToken,
    useClass: MongooseFileWriteRepositoryImpl,
  },
  {
    provide: IServiceEntryReadRepositoryToken,
    useClass: MongooseServiceEntryReadRepositoryImpl,
  },
  {
    provide: IServiceEntryWriteRepositoryToken,
    useClass: MongooseServiceEntryWriteRepositoryImpl,
  },
  {
    provide: IServiceEntryAccessReadRepositoryToken,
    useClass: MongooseServiceEntryAccessReadRepositoryImpl,
  },
  {
    provide: IServiceEntryAccessWriteRepositoryToken,
    useClass: MongooseServiceEntryAccessWriteRepositoryImpl,
  },
  {
    provide: IServiceEntrySurveyReadRepositoryToken,
    useClass: MongooseServiceEntrySurveyReadRepositoryImpl,
  },
  {
    provide: IServiceEntrySurveyWriteRepositoryToken,
    useClass: MongooseServiceEntrySurveyWriteRepositoryImpl,
  },
  {
    provide: IServiceEntrySurveyTemplateReadRepositoryToken,
    useClass: MongooseServiceEntrySurveyTemplateReadRepositoryImpl,
  },
  {
    provide: ICustomerFiscalProfileReadRepositoryToken,
    useClass: MongooseCustomerFiscalProfileReadRepositoryImpl,
  },
  {
    provide: ICustomerFiscalProfileWriteRepositoryToken,
    useClass: MongooseCustomerFiscalProfileWriteRepositoryImpl,
  },
  {
    provide: ICustomerReadRepositoryToken,
    useClass: MongooseCustomerReadRepositoryImpl,
  },
  {
    provide: ICustomerWriteRepositoryToken,
    useClass: MongooseCustomerWriteRepositoryImpl,
  },
  {
    provide: IServicePackageRecordWriteRepositoryToken,
    useClass: MongooseServicePackageRecordWriteRepositoryImpl,
  },
  {
    provide: IServicePackageRecordReadRepositoryToken,
    useClass: MongooseServicePackageRecordReadRepositoryImpl,
  },
  {
    provide: IProviderReadRepositoryToken,
    useClass: MongooseProviderReadRepositoryImpl,
  },
  {
    provide: IProviderWriteRepositoryToken,
    useClass: MongooseProviderWriteRepositoryImpl,
  },
  {
    provide: IProviderFiscalProfileReadRepositoryToken,
    useClass: MongooseProviderFiscalProfileReadRepositoryImpl,
  },
  {
    provide: IProviderFiscalProfileWriteRepositoryToken,
    useClass: MongooseProviderFiscalProfileWriteRepositoryImpl,
  },
  {
    provide: IProviderBankingInfoReadRepositoryToken,
    useClass: MongooseProviderBankingInfoReadRepositoryImpl,
  },
  {
    provide: IProviderBankingInfoWriteRepositoryToken,
    useClass: MongooseProviderBankingInfoWriteRepositoryImpl,
  },
  {
    provide: IContactReadRepositoryToken,
    useClass: MongooseContactReadRepositoryImpl,
  },
  {
    provide: IContactWriteRepositoryToken,
    useClass: MongooseContactWriteRepositoryImpl,
  },
  {
    provide: IRecipientGroupReadRepositoryToken,
    useClass: MongooseRecipientGroupReadRepositoryImpl,
  },
  {
    provide: IRecipientGroupWriteRepositoryToken,
    useClass: MongooseRecipientGroupWriteRepositoryImpl,
  },
  {
    provide: IExpirationStatusPolicyReadRepositoryToken,
    useClass: MongooseExpirationStatusPolicyReadRepositoryImpl,
  },
  {
    provide: IExpirationStatusPolicyWriteRepositoryToken,
    useClass: MongooseExpirationStatusPolicyWriteRepositoryImpl,
  },
  {
    provide: IExpirationNotificationPolicyReadRepositoryToken,
    useClass: MongooseExpirationNotificationPolicyReadRepositoryImpl,
  },
  {
    provide: IExpirationNotificationPolicyWriteRepositoryToken,
    useClass: MongooseExpirationNotificationPolicyWriteRepositoryImpl,
  },
  {
    provide: IInternalAssetMaintenanceRecordReadRepositoryToken,
    useClass: MongooseInternalAssetMaintenanceRecordReadRepositoryImpl,
  },
  {
    provide: IInternalAssetMaintenanceRecordWriteRepositoryToken,
    useClass: MongooseInternalAssetMaintenanceRecordWriteRepositoryImpl,
  },
  {
    provide: IInternalJobLockRepositoryToken,
    useClass: MongooseInternalJobLockRepositoryImpl,
  },
  MongooseTransactionContext,
  {
    provide: IUserCustomerRelationshipReadRepositoryToken,
    useClass: MongooseUserCustomerRelationshipReadRepositoryImpl,
  },
  {
    provide: IUserCustomerRelationshipWriteRepositoryToken,
    useClass: MongooseUserCustomerRelationshipWriteRepositoryImpl,
  },
  {
    provide: ITransactionalExecutorToken,
    useClass: MongooseTransactionalExecutor,
  },
];

export const MongooseRepositoryTokens = [
  IUserReadRepositoryToken,
  IUserWriteRepositoryToken,
  IRoleReadRepositoryToken,
  IRoleWriteRepositoryToken,
  IUserRegistrationInvitationReadRepositoryToken,
  IUserRegistrationInvitationWriteRepositoryToken,
  IUserPasswordResetTokenReadRepositoryToken,
  IUserPasswordResetTokenWriteRepositoryToken,
  IFileReadRepositoryToken,
  IFileWriteRepositoryToken,
  IServiceEntryReadRepositoryToken,
  IServiceEntryWriteRepositoryToken,
  IServiceEntryAccessReadRepositoryToken,
  IServiceEntryAccessWriteRepositoryToken,
  IServiceEntrySurveyReadRepositoryToken,
  IServiceEntrySurveyWriteRepositoryToken,
  IServiceEntrySurveyTemplateReadRepositoryToken,
  ICustomerFiscalProfileReadRepositoryToken,
  ICustomerFiscalProfileWriteRepositoryToken,
  ICustomerReadRepositoryToken,
  ICustomerWriteRepositoryToken,
  IServicePackageRecordWriteRepositoryToken,
  IServicePackageRecordReadRepositoryToken,
  IProviderReadRepositoryToken,
  IProviderWriteRepositoryToken,
  IProviderFiscalProfileReadRepositoryToken,
  IProviderFiscalProfileWriteRepositoryToken,
  IProviderBankingInfoReadRepositoryToken,
  IProviderBankingInfoWriteRepositoryToken,
  IContactReadRepositoryToken,
  IContactWriteRepositoryToken,
  IRecipientGroupReadRepositoryToken,
  IRecipientGroupWriteRepositoryToken,
  IExpirationStatusPolicyReadRepositoryToken,
  IExpirationStatusPolicyWriteRepositoryToken,
  IExpirationNotificationPolicyReadRepositoryToken,
  IExpirationNotificationPolicyWriteRepositoryToken,
  IInternalAssetMaintenanceRecordReadRepositoryToken,
  IInternalAssetMaintenanceRecordWriteRepositoryToken,
  IInternalJobLockRepositoryToken,
  IUserCustomerRelationshipReadRepositoryToken,
  IUserCustomerRelationshipWriteRepositoryToken,
  ITransactionalExecutorToken,
];
